version: '3.7'
services:

  db:
    image: postgres
    restart: always
    environment:
     - POSTGRES_PASSWORD
     - POSTGRES_USER
     - POSTGRES_DB

  front:
    build: Frontend
    restart: always

  back:
    build: Backend
    restart: always
    ports:
     - 5003:5003
    environment:
     - SECRET
     - PSQL_LINK
