version: '3.7'
services:

  db:
    image: postgres
    restart: always
    environment:
     - POSTGRES_PASSWORD
     - POSTGRES_USER
     - POSTGRES_DB

  front:
    build: Frontend
    volumes:
     - ./Frontend/shared:/app/shared/
     
  back:
    build: Backend
    restart: always
    ports:
     - "5000:5000"
    environment:
     - SECRET
     - PSQL_LINK
    volumes:
     - ./Frontend/shared/templates:/backend/templates
     - ./Frontend/shared/static:/backend/static

